//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalString() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalString", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя пользователя или пароль указаны неверно..
        /// </summary>
        internal static string AccountErrorForNameOrPass {
            get {
                return ResourceManager.GetString("AccountErrorForNameOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Неправильный текущий пароль или недопустимый новый пароль..
        /// </summary>
        internal static string AccountErrorNowPassword {
            get {
                return ResourceManager.GetString("AccountErrorNowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Admin.
        /// </summary>
        internal static string ADMIN_NAME {
            get {
                return ResourceManager.GetString("ADMIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вы уверены?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вернутся назад.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вы заказали в магазине -.
        /// </summary>
        internal static string BuyProduct {
            get {
                return ResourceManager.GetString("BuyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Корзина.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Категории.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как CategoryMiniImages.
        /// </summary>
        internal static string CATEGORY_MINI_IMAGES_FOLDER {
            get {
                return ResourceManager.GetString("CATEGORY_MINI_IMAGES_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как This message would not have to answer.
        /// </summary>
        internal static string DoNotRespondEn {
            get {
                return ResourceManager.GetString("DoNotRespondEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как На это сообщение не надо отвечать.
        /// </summary>
        internal static string DoNotRespondRu {
            get {
                return ResourceManager.GetString("DoNotRespondRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Домашняя страница.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как smtp.mail.ru.
        /// </summary>
        internal static string hostSmtp {
            get {
                return ResourceManager.GetString("hostSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Your code to replenish the internal account.
        /// </summary>
        internal static string KeyCodeToUserEn {
            get {
                return ResourceManager.GetString("KeyCodeToUserEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Ваш код для пополнения внутреннего счета.
        /// </summary>
        internal static string KeyCodeToUserRu {
            get {
                return ResourceManager.GetString("KeyCodeToUserRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выход.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вход.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заказы.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Статусы заказа.
        /// </summary>
        internal static string OrdersStatus {
            get {
                return ResourceManager.GetString("OrdersStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как He status of your purchase has been changed. Now he has the status of.
        /// </summary>
        internal static string OrderStatusEn {
            get {
                return ResourceManager.GetString("OrderStatusEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Статус вашей покупки был изменен. Теперь он имеет статус.
        /// </summary>
        internal static string OrderStatusRu {
            get {
                return ResourceManager.GetString("OrderStatusRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 784134230z.
        /// </summary>
        internal static string passSmtp {
            get {
                return ResourceManager.GetString("passSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Система оплаты.
        /// </summary>
        internal static string PaymentSystem {
            get {
                return ResourceManager.GetString("PaymentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Личная страница.
        /// </summary>
        internal static string PersonalPage {
            get {
                return ResourceManager.GetString("PersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Товары.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ProductImages.
        /// </summary>
        internal static string PRODUCT_IMAGES_FOLDER {
            get {
                return ResourceManager.GetString("PRODUCT_IMAGES_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Mini.
        /// </summary>
        internal static string PRODUCT_IMAGES_MINI_FOLDER {
            get {
                return ResourceManager.GetString("PRODUCT_IMAGES_MINI_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Address.
        /// </summary>
        internal static string PROFILE_ADDRESS {
            get {
                return ResourceManager.GetString("PROFILE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как FirstName.
        /// </summary>
        internal static string PROFILE_FIRST_NAME {
            get {
                return ResourceManager.GetString("PROFILE_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как LastName.
        /// </summary>
        internal static string PROFILE_LAST_NAME {
            get {
                return ResourceManager.GetString("PROFILE_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Money.
        /// </summary>
        internal static string PROFILE_MONEY {
            get {
                return ResourceManager.GetString("PROFILE_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Phone.
        /// </summary>
        internal static string PROFILE_PHONE {
            get {
                return ResourceManager.GetString("PROFILE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поиск товара.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Cart.
        /// </summary>
        internal static string SESSION_CART {
            get {
                return ResourceManager.GetString("SESSION_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Home.
        /// </summary>
        internal static string SESSION_TOP {
            get {
                return ResourceManager.GetString("SESSION_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подкатегории.
        /// </summary>
        internal static string Subcategory {
            get {
                return ResourceManager.GetString("Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SubcategoryMiniImages.
        /// </summary>
        internal static string SUBCATEGORY_MINI_IMAGES_FOLDER {
            get {
                return ResourceManager.GetString("SUBCATEGORY_MINI_IMAGES_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Количество денег.
        /// </summary>
        internal static string TheAmountOfMoney {
            get {
                return ResourceManager.GetString("TheAmountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как E-shop.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отправка почты.
        /// </summary>
        internal static string ToMail {
            get {
                return ResourceManager.GetString("ToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как xet-pk@mail.ru.
        /// </summary>
        internal static string userSmtp {
            get {
                return ResourceManager.GetString("userSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добро пожаловать.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
