//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Other {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Other() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Other", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &lt; Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Создатель сайта - Прохоров С.Л..
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Элементы {0} - {1} из {2}.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Найти.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как  &lt;&lt; На первую страницу.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .Сайт не является действительным интернет магазином, он был разработал только как пример..
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как формата.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Не было найдено не одного совпадения.
        /// </summary>
        internal static string FoundNot {
            get {
                return ResourceManager.GetString("FoundNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &gt;&gt; последнюю страницу.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &gt; Вперед.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поиск добавленных с .
        /// </summary>
        internal static string SearchAdded {
            get {
                return ResourceManager.GetString("SearchAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как до.
        /// </summary>
        internal static string SearchAddedTo {
            get {
                return ResourceManager.GetString("SearchAddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поиск по названию.
        /// </summary>
        internal static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Мини-изображение в разделе категории.
        /// </summary>
        internal static string ThumbnailSectionCategory {
            get {
                return ResourceManager.GetString("ThumbnailSectionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Мини-изображение в разделе подкатегории.
        /// </summary>
        internal static string ThumbnailSectionSubcategory {
            get {
                return ResourceManager.GetString("ThumbnailSectionSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загрузить.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загрузить картинку.
        /// </summary>
        internal static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
    }
}
