//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string NameRu { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string NameEn { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
