//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SubcategoryProducts = new HashSet<SubcategoryProduct>();
        }
    
        public int ID { get; set; }
        public string NameRu { get; set; }
        public string DescriptionRu { get; set; }
        public string ImageExt { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool AvailableDiscounts { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<int> CurrentBalance { get; set; }
        public string NameEn { get; set; }
        public string DescriptionEn { get; set; }
    
        public virtual ICollection<SubcategoryProduct> SubcategoryProducts { get; set; }
    }
}
