//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_shop.Views.Category.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_cshtml() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_shop.Views.Category.App_LocalResources.Index.cshtml", typeof(Index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преимущества посудомоечной машины.
        /// </summary>
        public static string Dishwasher1 {
            get {
                return ResourceManager.GetString("Dishwasher1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всю работу посудомоечной машины условно можно разделить на несколько этапов. Сначала вся посуда загружается в определенные отсеки для каждого типа посуды - ложки, вилки, ножи и мелкие столовые приборы закладываются в специальную корзинку.  В верхний лоток закладываются небольшие тарелки, чашки, блюдца, бокалы. Ну а в нижний - миски, большие тарелки, блюда, сковороды, кастрюли. Посуду необходимо складывать так, чтобы струя воды могла омывать посуду со всех сторон, смыть жир и  остатки пищи. Следующий этап –  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Dishwasher2 {
            get {
                return ResourceManager.GetString("Dishwasher2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При выборе посудомоечной машины, следует обращать внимание на уровень энергопотребления, мойку, сушку, которые в свою очередь разделяются на несколькоклассов. Рассмотрим их более подробно. Уровень энергопотребления, в зависимости от экономии, разделяют на следующие классы:&lt;br /&gt;• А считается самым экономичным, при котором потребление электороэнергии сводится к минимуму&lt;br /&gt;• В считается среднеэкономичным&lt;br /&gt;• С наименее экономичный&lt;br /&gt;Большинство посудомоечных машин имеют класс потребления энергии A ил [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Dishwasher3 {
            get {
                return ResourceManager.GetString("Dishwasher3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование изображения.
        /// </summary>
        public static string ImageEditing {
            get {
                return ResourceManager.GetString("ImageEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как выбрать мобильный телефон?.
        /// </summary>
        public static string Mobile1 {
            get {
                return ResourceManager.GetString("Mobile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функциональность – необходимая или излишняя?.
        /// </summary>
        public static string Mobile2 {
            get {
                return ResourceManager.GetString("Mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абсолютно все современные телефоны, включая самые доступные, обладают джентльменским набором возможностей, к которым относятся: телефонная книга, редактор SMS, часы и калькулятор и т.д. Все остальные функции, включая браузеры, полифонию, фонарики, поддержку карт памяти и многое другое относятся к дополнительным, что для покупателя обозначает  одну простую вещь – за них придется доплатить. Соответственно, если вам или вашим родственникам нужен аппарат исключительно для звонков, то нет смысла переплачивать за [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Mobile3 {
            get {
                return ResourceManager.GetString("Mobile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В современных условиях выбор телефона сводится к нахождению ответа всего на три вопроса: «Как я буду использовать  свой будущий аппарат?» (только говорить, фотографировать, слушать музыку, работать, красоваться и т.д.), «Самый удобный формфактор?» (моноблок, раскладушка, слайдер, сенсорный) и наконец «Любимый телефонный бренд?» (Nokia, Samsung, Sony Ericsson и др.). А уж ответы на эти вопросы и покажут вам, сколько денег придется выложить за оптимальный выбор..
        /// </summary>
        public static string Mobile4 {
            get {
                return ResourceManager.GetString("Mobile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как выбрать планшет?.
        /// </summary>
        public static string PlaneTable1 {
            get {
                return ResourceManager.GetString("PlaneTable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С легкой руки Apple рынок планшетных компьютеров сегодня развивается огромными темпами. На нем присутствует большое количество разнообразных моделей. При этом покупателю, не знакомому со спецификой этого рынка, приходится непросто: нужно определяться не только с характеристиками и функциональностью устройства, но и с платформой, на которой оно работает. Чтобы облегчить выбор, давайте посмотрим, что такое планшет, как его эффективно использовать  и из каких соображений выбирать..
        /// </summary>
        public static string PlaneTable2 {
            get {
                return ResourceManager.GetString("PlaneTable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планшет – это экран!.
        /// </summary>
        public static string PlaneTable3 {
            get {
                return ResourceManager.GetString("PlaneTable3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если взять и отделить от типичного ноутбука клавиатурный блок, в ваших руках останется только его экран. По сути, большинство планшетов именно так и выглядят: сенсорный экран занимает в них до 90% лицевой панели, а управлять устройством нужно с помощью прикосновения к нему..
        /// </summary>
        public static string PlaneTable4 {
            get {
                return ResourceManager.GetString("PlaneTable4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платформа (операционная система).
        /// </summary>
        public static string PlaneTable5 {
            get {
                return ResourceManager.GetString("PlaneTable5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики и оснащение.
        /// </summary>
        public static string PlaneTable6 {
            get {
                return ResourceManager.GetString("PlaneTable6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос дисплея мы уже обсудили, но на этом планшет не заканчивается. Все современные модели Android-планшетов основываются на одно- или двухъядерном процессоре (называемом также SoC, «система-на-чипе») архитектуры ARM и производства Qualcomm, NVIDIA, Texas Instruments либо Samsung. Модели Apple также работают на ARM-процессорах, но собственного дизайна калифорнийской компании. Ну, а Windows-разновидности, как уже было упомянуто, чаще всего построены на базе Intel Atom (x86). Частота процессора и объем памят [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string PlaneTable7 {
            get {
                return ResourceManager.GetString("PlaneTable7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужен ли вам новый телевизор?.
        /// </summary>
        public static string TV1 {
            get {
                return ResourceManager.GetString("TV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кадры решают все!.
        /// </summary>
        public static string TV2 {
            get {
                return ResourceManager.GetString("TV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Представим, что происходит, когда на типичном жидкокристаллическом телевизоре демонстрируется динамичное, быстро изменяющееся изображение. Это не такая уж редкость: гепард, преследующий антилопу на Animal Planet, с треляющие из куриной пушки «Разрушители легенд» на Discovery и даже стремительно несущиеся и меняющиеся на ходу трансформеры с DVD - в любом из этих случаев стандартных 50 Гц для отображения быстрых движений может оказаться недостаточно. То же самое касается спортивных соревнований: представьте,  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TV3 {
            get {
                return ResourceManager.GetString("TV3", resourceCulture);
            }
        }
    }
}
